
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: FlippostModules
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
server:
  port: 8045